"use client";
import {useMemo,useState} from "react";
import {Search,SlidersHorizontal,Bookmark,GitCompare,Network,ArrowUpRight,ChevronDown,Plus,Check,Clock3} from "lucide-react";
import "./styles.css";

type Paper={id:number,title:string,authors:string,year:number,venue:string,score:number,cites:number,tags:string[],abstract:string};
const papers:Paper[]=[
{id:1,title:"Foundation Models for Clinical Decision Support: A Prospective Evaluation",authors:"M. Chen · R. Iyer · S. Patel",year:2026,venue:"Nature Medicine",score:96,cites:84,tags:["clinical AI","evaluation"],abstract:"Prospective evidence on how foundation models behave under real clinical workflows, with emphasis on calibration, abstention and human oversight."},
{id:2,title:"Multimodal Representation Learning for Biomedical Imaging",authors:"A. Rossi · L. Nguyen · K. Shah",year:2025,venue:"MICCAI",score:91,cites:126,tags:["imaging","multimodal"],abstract:"A unified representation strategy across radiology modalities, evaluated on transfer, robustness and low-data adaptation."},
{id:3,title:"Retrieval-Augmented Generation for Evidence Synthesis",authors:"J. Wilson · P. Rao · E. Kim",year:2026,venue:"ACL",score:89,cites:41,tags:["RAG","NLP"],abstract:"A systematic study of retrieval strategies, citation fidelity and failure modes in evidence-heavy generation."},
{id:4,title:"Federated Learning Across Heterogeneous Hospital Networks",authors:"D. Alvarez · N. Singh · Y. Ito",year:2024,venue:"JAMA",score:87,cites:203,tags:["federated","privacy"],abstract:"Federated optimization under highly heterogeneous hospital data distributions, with practical deployment constraints."},
{id:5,title:"Uncertainty-Aware Deep Learning for Rare Disease Detection",authors:"C. Okafor · T. Mehta · A. Brooks",year:2025,venue:"Lancet Digital Health",score:85,cites:67,tags:["uncertainty","diagnosis"],abstract:"Uncertainty estimation as a mechanism for safer rare-disease screening and clinician escalation."},
{id:6,title:"Causal Discovery from Longitudinal Patient Records",authors:"H. Park · V. Das · M. Stein",year:2023,venue:"Nature Machine Intelligence",score:82,cites:312,tags:["causal","EHR"],abstract:"Methods for discovering stable causal structure from longitudinal observational records with missingness."}
];
export default function Home(){const[q,setQ]=useState("");const[filter,setFilter]=useState("All");const[saved,setSaved]=useState<number[]>([]);const[selected,setSelected]=useState<number[]>([1,2]);const[active,setActive]=useState<Paper|null>(null);const results=useMemo(()=>papers.filter(p=>(filter==='All'||p.tags.includes(filter.toLowerCase()))&&(p.title+p.authors+p.abstract+p.tags.join(' ')).toLowerCase().includes(q.toLowerCase())),[q,filter]);
return <div className="shell"><header><div className="mark">ATLAS<span>/</span>RESEARCH</div><nav><button className="active">DISCOVER</button><button>COLLECTIONS</button><button>GRAPH</button></nav><div className="user">AY <span>●</span></div></header><main><section className="intro"><div><p className="kicker">RESEARCH INTELLIGENCE · 11 AUG 2026</p><h1>Find the work<br/><i>behind</i> the work.</h1><p className="lede">A research workspace for finding, comparing and connecting scientific literature without losing the thread.</p></div><div className="signal"><div className="signalNo">01</div><div className="miniGraph">{Array.from({length:24}).map((_,i)=><i key={i} style={{height:`${18+Math.sin(i*.7)*15+i%5*8}px`}}/>)}</div><span>6.2M indexed records · 14 disciplines</span></div></section>
<section className="workspace"><aside><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search papers, authors, concepts..."/></div><div className="filters"><div className="filterHead"><span>FILTER BY</span><SlidersHorizontal size={14}/></div>{['All','Clinical AI','Imaging','RAG','Privacy','Causal'].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'sel':''}><span>{x}</span><small>{x==='All'?6:papers.filter(p=>p.tags.includes(x.toLowerCase())).length}</small></button>)}</div><div className="savedBox"><span>SAVED</span><b>{saved.length} papers</b><button onClick={()=>setSaved([])}>CLEAR</button></div></aside>
<div className="results"><div className="resultTop"><span>{results.length} RESULTS · RELEVANCE</span><button>RECENT <ChevronDown size={13}/></button></div>{results.map(p=><article key={p.id} className="paper" onClick={()=>setActive(p)}><div className="paperMeta"><span>{p.year}</span><span>{p.venue}</span><span className="score">MATCH {p.score}%</span></div><h2>{p.title}<ArrowUpRight size={18}/></h2><p className="authors">{p.authors}</p><p className="abstract">{p.abstract}</p><div className="paperFoot"><div>{p.tags.map(t=><span key={t}>{t}</span>)}</div><span>{p.cites} citations</span><button onClick={e=>{e.stopPropagation();setSaved(s=>s.includes(p.id)?s.filter(x=>x!==p.id):[...s,p.id])}}>{saved.includes(p.id)?<Check size={15}/>:<Bookmark size={15}/>}</button></div></article>)}</div></section>
<section className="compare"><div className="compareHead"><div><p className="kicker">02 / WORKSPACE</p><h2>Compare evidence.</h2></div><p>Select papers to keep a live comparison beside your discovery stream.</p></div><div className="compareGrid">{selected.map(id=>{const p=papers.find(x=>x.id===id)!;return <div className="comparePaper" key={id}><div><span>{p.venue} · {p.year}</span><button onClick={()=>setSelected(s=>s.filter(x=>x!==id))}>×</button></div><h3>{p.title}</h3><dl><dt>CITATIONS</dt><dd>{p.cites}</dd><dt>RELEVANCE</dt><dd>{p.score}%</dd><dt>METHOD</dt><dd>{p.tags.join(' / ')}</dd></dl></div>})}<div className="addCompare"><Plus size={18}/><span>Add a paper to compare</span></div></div></section>
<section className="network"><div><p className="kicker">03 / CONNECTIONS</p><h2>See the field<br/><i>as a network.</i></h2><p>Topics, methods and papers become visible as relationships instead of isolated search results.</p></div><div className="networkViz"><div className="orbit o1"/><div className="orbit o2"/><div className="node center">AI</div>{['RAG','EHR','VISION','CAUSAL','PRIVACY','CLINICAL'].map((x,i)=><div className="node" key={x} style={{left:`${50+Math.cos(i*1.047)*34}%`,top:`${50+Math.sin(i*1.047)*34}%`}}>{x}</div>)}<Network size={18}/></div></section></main><footer><span>ATLAS RESEARCH / PRIVATE WORKSPACE</span><span><Clock3 size={11}/> INDEX UPDATED 3 MIN AGO</span></footer>{active&&<div className="drawer" onClick={()=>setActive(null)}><div className="drawerInner" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}>×</button><p className="kicker">PAPER {String(active.id).padStart(2,'0')} · {active.venue}</p><h2>{active.title}</h2><p className="authors">{active.authors}</p><div className="drawerStats"><b>{active.score}%<small>RELEVANCE</small></b><b>{active.cites}<small>CITATIONS</small></b><b>{active.year}<small>PUBLISHED</small></b></div><p className="drawerText">{active.abstract}</p><button className="primary" onClick={()=>setSaved(s=>s.includes(active.id)?s:[...s,active.id])}>{saved.includes(active.id)?'SAVED TO COLLECTION':'SAVE TO COLLECTION'} <Bookmark size={15}/></button></div></div>}</div>}
